export const TRANSLATIONS = {
  en: {
    welcomeBack: "Welcome Back",
    dashboard: "Dashboard",
    collections: "Collections",
    analytics: "Analytics",
    notifications: "Notifications",
    profile: "Profile",
    goodMorning: "Good Morning",
    todaysWaste: "Today's Waste",
    foodDiverted: "Food Diverted",
    moneySaved: "Money Saved",
    totalGenerated: "Total Generated",
    recommendedServings: "Recommended Servings",
    expectedWaste: "Expected Waste",
    attendance: "Est. Attendance",
    weekday: "Weekday",
    menu: "Meal Menu",
    loggingStatus: "Today's Logging Status",
    submitted: "SUBMITTED",
    pending: "PENDING",
    uploadWaste: "Upload Waste Logs",
    activePickups: "Active Pickups",
    timeline: "Progress Timeline",
    posted: "Posted",
    reserved: "Reserved",
    transit: "Transit",
    confirmation: "Confirmation",
    completed: "Completed",
    history: "Historical Collections",
    alerts: "System Alerts",
    support: "Raise Support Ticket",
    comConfigurations: "Save Configurations",
    darkTheme: "Dark Theme Mode",
    language: "System Language",
    faq: "Frequently Asked Questions",
    cancellationReason: "Surplus Reason",
    confirmReserve: "Confirm Reservation",
    back: "Back",
    next: "Next",
    submit: "Submit",
    cancel: "Cancel",
    reserve: "Reserve Pickup",
    transitStart: "Start Transit",
    completePickup: "Complete Pickup",
    navigate: "Navigate in Google Maps",
    confirmMsg: "Are you sure you want to reserve this pickup? You will have 30 minutes to complete the collection."
  },
  ta: {
    welcomeBack: "மீண்டும் வருக",
    dashboard: "டாஷ்போர்டு",
    collections: "சேகரிப்புகள்",
    analytics: "பகுப்பாய்வு",
    notifications: "அறிவிப்புகள்",
    profile: "சுயவிவரம்",
    goodMorning: "காலை வணக்கம்",
    todaysWaste: "இன்றைய கழிவு",
    foodDiverted: "மாற்றப்பட்ட உணவு",
    moneySaved: "சேமிக்கப்பட்ட பணம்",
    totalGenerated: "மொத்த கழிவு",
    recommendedServings: "பரிந்துரைக்கப்பட்ட உணவுகள்",
    expectedWaste: "எதிர்பார்க்கப்படும் கழிவு",
    attendance: "வருகை",
    weekday: "வாரம்",
    menu: "உணவு மெனு",
    loggingStatus: "இன்றைய பதிவு நிலை",
    submitted: "சமர்ப்பிக்கப்பட்டது",
    pending: "நிலுவையில் உள்ளது",
    uploadWaste: "கழிவுகளை பதிவேற்றுக",
    activePickups: "செயலில் உள்ள சேகரிப்புகள்",
    timeline: "முன்னேற்றக் காலவரிசை",
    posted: "பதிவிடப்பட்டது",
    reserved: "முன்பதிவு செய்யப்பட்டது",
    transit: "வழியில்",
    confirmation: "உறுதிப்படுத்தல்",
    completed: "முடிந்தது",
    history: "வரலாற்று சேகரிப்புகள்",
    alerts: "அறிவிப்புகள்",
    support: "ஆதரவு கோரிக்கை",
    comConfigurations: "அமைப்புகளைச் சேமி",
    darkTheme: "இருண்ட பயன்முறை",
    language: "கணினி மொழி",
    faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    cancellationReason: "கழிவுக்கான காரணம்",
    confirmReserve: "முன்பதிவை உறுதி செய்",
    back: "பின்னால்",
    next: "அடுத்து",
    submit: "சமர்ப்பி",
    cancel: "ரத்து செய்",
    reserve: "முன்பதிவு செய்",
    transitStart: "பயணத்தைத் தொடங்கு",
    completePickup: "சேகரிப்பை முடி",
    navigate: "கூகுள் மேப்பில் காட்டு",
    confirmMsg: "இந்த சேகரிப்பை முன்பதிவு செய்ய விரும்புகிறீர்களா? இதை முடிக்க உங்களுக்கு 30 நிமிடங்கள் உள்ளன."
  },
  kn: {
    welcomeBack: "ಸ್ವಾಗತ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    collections: "ಸಂಗ್ರಹಣೆಗಳು",
    analytics: "ವಿಶ್ಲೇಷಣೆ",
    notifications: "ಸೂಚನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    goodMorning: "ಶುಭೋದಯ",
    todaysWaste: "ಇಂದಿನ ತ್ಯಾಜ್ಯ",
    foodDiverted: "ಉಳಿಸಿದ ಆಹಾರ",
    moneySaved: "ಉಳಿಸಿದ ಹಣ",
    totalGenerated: "ಒಟ್ಟು ತ್ಯಾಜ್ಯ",
    recommendedServings: "ಶಿಫಾರಸು ಮಾಡಿದ ಊಟ",
    expectedWaste: "ನಿರೀಕ್ಷಿತ ತ್ಯಾಜ್ಯ",
    attendance: "ಹಾಜರಾತಿ",
    weekday: "ವಾರದ ದಿನ",
    menu: "ಮೆನು",
    loggingStatus: "ಇಂದಿನ ಸ್ಥಿತಿ",
    submitted: "ಸಲ್ಲಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ ಇದೆ",
    uploadWaste: "ತ್ಯಾಜ್ಯ ದಾಖಲಿಸಿ",
    activePickups: "ಸಕ್ರಿಯ ಸಂಗ್ರಹಗಳು",
    timeline: "ಪ್ರಗತಿಯ ಟೈಮ್‌ಲೈನ್",
    posted: "ದಾಖಲಿಸಲಾಗಿದೆ",
    reserved: "ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
    transit: "ದಾರಿಯಲ್ಲಿ",
    confirmation: "ದೃಢೀಕರಣ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    history: "ಹಳೆಯ ಸಂಗ್ರಹಗಳು",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    support: "ಬೆಂಬಲ ಕೋರಿಕೆ",
    comConfigurations: "ಸಂರಚನೆಗಳನ್ನು ಉಳಿಸಿ",
    darkTheme: "ಡಾರ್ಕ್ ಥೀಮ್",
    language: "ಭಾಷೆ",
    faq: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    cancellationReason: "ತ್ಯಾಜ್ಯದ ಕಾರಣ",
    confirmReserve: "ಕಾಯ್ದಿರಿಸುವಿಕೆ ದೃಢೀಕರಿಸಿ",
    back: "ಹಿಂದೆ",
    next: "ಮುಂದೆ",
    submit: "ಸಲ್ಲಿಸು",
    cancel: "ರದ್ದುಮಾಡು",
    reserve: "ಕಾಯ್ದಿರಿಸಿ",
    transitStart: "ದಾರಿಯಲ್ಲಿ ಹೊರಡಿ",
    completePickup: "ಸಂಗ್ರಹ ಪೂರ್ಣಗೊಳಿಸಿ",
    navigate: "ಗೂಗಲ್ ನಕ್ಷೆಯಲ್ಲಿ ನೋಡಿ",
    confirmMsg: "ಈ ತ್ಯಾಜ್ಯವನ್ನು ಕಾಯ್ದಿರಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ? ಸಂಗ್ರಹಿಸಲು ನಿಮಗೆ 30 ನಿಮಿಷಗಳಿವೆ."
  },
  hi: {
    welcomeBack: "स्वागत है",
    dashboard: "डैशबोर्ड",
    collections: "संग्रह",
    analytics: "विश्लेषण",
    notifications: "सूचनाएं",
    profile: "प्रोफाइल",
    goodMorning: "शुभ प्रभात",
    todaysWaste: "आज का कचरा",
    foodDiverted: "बचाया गया भोजन",
    moneySaved: "बचाया गया धन",
    totalGenerated: "कुल उत्पन्न कचरा",
    recommendedServings: "अनुशंसित भोजन",
    expectedWaste: "अपेक्षित कचरा",
    attendance: "अनुमानित उपस्थिति",
    weekday: "सप्ताह का दिन",
    menu: "भोजन का मेनू",
    loggingStatus: "आज की स्थिति",
    submitted: "जमा किया गया",
    pending: "लंबित",
    uploadWaste: "कचरा अपलोड करें",
    activePickups: "सक्रिय पिकअप",
    timeline: "प्रगति समयरेखा",
    posted: "पोस्ट किया गया",
    reserved: "आरक्षित",
    transit: "मार्ग में",
    confirmation: "पुष्टि",
    completed: "पूर्ण",
    history: "ऐतिहासिक संग्रह",
    alerts: "सिस्टम अलर्ट",
    support: "सहायता टिकट उठाएं",
    comConfigurations: "कॉन्फ़िगरेशन सहेजें",
    darkTheme: "डार्क थीम मोड",
    language: "सिस्टम भाषा",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    cancellationReason: "कचरे का कारण",
    confirmReserve: "आरक्षण की पुष्टि करें",
    back: "पीछे",
    next: "आगे",
    submit: "जमा करें",
    cancel: "रद्द करें",
    reserve: "पिकअप आरक्षित करें",
    transitStart: "यात्रा शुरू करें",
    completePickup: "पिकअप पूरा करें",
    navigate: "गूगल मैप्स में देखें",
    confirmMsg: "क्या आप वाकई इस पिकअप को आरक्षित करना चाहते हैं? संग्रह पूरा करने के लिए आपके पास 30 मिनट हैं।"
  }
};
